# Final Project Python Cleaning

####  Import Libraries

In [1]:
import numpy as np

import pandas as pd

####  Read Files

In [2]:
df_customers = pd.read_csv('DataCo_Customers.csv')
df_products = pd.read_csv('DataCo_Products.csv')
df_orders = pd.read_csv('DataCo_Order_Items.csv')

## Customers Table

####  Explore Data DataCo_Customers Table

In [6]:
## How many rows and columns?
df_customers.shape

(180519, 13)

In [7]:
## What are the column names?
df_customers.columns

Index(['Customer Id', 'Customer Fname', 'Customer Lname', 'Customer Segment',
       'Customer Country', 'Customer City', 'Customer Street',
       'Customer State', 'Customer Zipcode', 'Latitude', 'Longitude',
       'Customer Email', 'Customer Password'],
      dtype='str')

In [8]:
## What is the data type of each column?
df_customers.dtypes

Customer Id            int64
Customer Fname           str
Customer Lname           str
Customer Segment         str
Customer Country         str
Customer City            str
Customer Street          str
Customer State           str
Customer Zipcode     float64
Latitude             float64
Longitude            float64
Customer Email           str
Customer Password        str
dtype: object

In [9]:
## Look at the first 5 rows
df_customers.head()

,Customer Id,Customer Fname,Customer Lname,Customer Segment,Customer Country,Customer City,Customer Street,Customer State,Customer Zipcode,Latitude,Longitude,Customer Email,Customer Password
0,20755,Cally,Holloway,Consumer,Puerto Rico,Caguas,5365 Noble Nectar Island,PR,72511.0,18.251453,-66.037056,XXXXXXXXX,XXXXXXXXX
1,19492,Irene,Luna,Consumer,Puerto Rico,Caguas,2679 Rustic Loop,PR,72511.0,18.279451,-66.037064,XXXXXXXXX,XXXXXXXXX
2,19491,Gillian,Maldonado,Consumer,EE. UU.,San Jose,8510 Round Bear Gate,CA,95125.0,37.292233,-121.881279,XXXXXXXXX,XXXXXXXXX
3,19490,Tana,Tate,Home Office,EE. UU.,Los Angeles,3200 Amber Bend,CA,90027.0,34.125946,-118.291016,XXXXXXXXX,XXXXXXXXX
4,19489,Orli,Hendricks,Corporate,Puerto Rico,Caguas,8671 Iron Anchor Corners,PR,72511.0,18.253769,-66.037048,XXXXXXXXX,XXXXXXXXX

In [10]:
## Look at the last 5 rows
df_customers.tail()

,Customer Id,Customer Fname,Customer Lname,Customer Segment,Customer Country,Customer City,Customer Street,Customer State,Customer Zipcode,Latitude,Longitude,Customer Email,Customer Password
180514,1005,Maria,Peterson,Home Office,EE. UU.,Brooklyn,1322 Broad Glade,NY,11207.0,40.640930,-73.942711,XXXXXXXXX,XXXXXXXXX
180515,9141,Ronald,Clark,Corporate,EE. UU.,Bakersfield,7330 Broad Apple Moor,CA,93304.0,35.362545,-119.018700,XXXXXXXXX,XXXXXXXXX
180516,291,John,Smith,Corporate,EE. UU.,Bristol,97 Burning Landing,CT,60101.0,41.629959,-72.967155,XXXXXXXXX,XXXXXXXXX
180517,2813,Mary,Smith,Consumer,Puerto Rico,Caguas,2585 Silent Autumn Landing,PR,72511.0,18.213350,-66.370575,XXXXXXXXX,XXXXXXXXX
180518,7547,Andrea,Ortega,Consumer,Puerto Rico,Caguas,697 Little Meadow,PR,72511.0,18.290380,-66.370613,XXXXXXXXX,XXXXXXXXX

In [11]:
##  random rows
df_customers.sample(3)

,Customer Id,Customer Fname,Customer Lname,Customer Segment,Customer Country,Customer City,Customer Street,Customer State,Customer Zipcode,Latitude,Longitude,Customer Email,Customer Password
129919,10251,Mary,Nguyen,Consumer,EE. UU.,Washington,4852 Velvet Campus,DC,20002.0,38.885216,-77.121765,XXXXXXXXX,XXXXXXXXX
142518,3431,Mary,Berger,Consumer,Puerto Rico,Caguas,6195 Broad Deer Townline,PR,72511.0,18.288033,-66.370575,XXXXXXXXX,XXXXXXXXX
92136,5548,Michael,Crawford,Corporate,Puerto Rico,Caguas,4945 Velvet Prairie Village,PR,72511.0,18.221539,-66.370560,XXXXXXXXX,XXXXXXXXX

In [12]:
##  data types
df_customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 13 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Customer Id        180519 non-null  int64
 1   Customer Fname     180519 non-null  str
 2   Customer Lname     180511 non-null  str
 3   Customer Segment   180519 non-null  str
 4   Customer Country   180519 non-null  str
 5   Customer City      180519 non-null  str
 6   Customer Street    180519 non-null  str
 7   Customer State     180519 non-null  str
 8   Customer Zipcode   180516 non-null  float64
 9   Latitude           180334 non-null  float64
 10  Longitude          180334 non-null  float64
 11  Customer Email     180519 non-null  str
 12  Customer Password  180519 non-null  str
dtypes: float64(3), int64(1), str(9)
memory usage: 17.9 MB

In [13]:
## Statistics for the number columns
df_customers.describe().T

,count,mean,std,min,25%,50%,75%,max
Customer Id,180519.0,6691.379495,4162.918106,1.000000,3258.500000,6457.000000,9779.000000,20757.000000
Customer Zipcode,180516.0,65433.335078,24465.370177,10002.000000,55337.000000,72511.000000,79109.000000,99205.000000
Latitude,180334.0,29.720940,9.813283,-33.937553,18.265432,33.144863,39.279617,48.781933
Longitude,180334.0,-84.919686,21.432971,-158.025986,-98.464638,-76.847908,-66.370583,115.263077

In [14]:
## Statistics for the text columns
df_customers.describe(include = 'str').T

                    count unique                      top    freq
Customer Fname     180519    782                     Mary   65150
Customer Lname     180511   1109                    Smith   64104
Customer Segment   180519      3                 Consumer   93504
Customer Country   180519      2                  EE. UU.  111146
Customer City      180519    563                   Caguas   66770
Customer Street    180519   6930  9126 Wishing Expressway     124
Customer State     180519     46                       PR   69373
Customer Email     180519      1                XXXXXXXXX  180519
Customer Password  180519      1                XXXXXXXXX  180519

In [15]:
## Unique values in small columns
df_customers['Customer Country'].unique()

<StringArray>
['Puerto Rico', 'EE. UU.']
Length: 2, dtype: str

In [16]:
df_customers['Customer Segment'].unique()

<StringArray>
['Consumer', 'Home Office', 'Corporate']
Length: 3, dtype: str

####  Data Cleaning and Transformation

In [17]:
## Remove extra spaces from all text columns
text_columns = df_customers.select_dtypes(exclude='number').columns

for col in text_columns:
    df_customers[col] = df_customers[col].str.strip()

In [18]:
## Missing values: count the nulls in each column
df_customers.isna().sum()

Customer Id            0
Customer Fname         0
Customer Lname         8
Customer Segment       0
Customer Country       0
Customer City          0
Customer Street        0
Customer State         0
Customer Zipcode       3
Latitude             185
Longitude            185
Customer Email         0
Customer Password      0
dtype: int64

In [19]:
df_customers['Latitude'].sample(50).isnull()

59649     False
9252      False
132891    False
105117    False
76090     False
4346      False
49664     False
52040     False
106521    False
117267    False
78353     False
141986    False
175539    False
167687    False
92297     False
119921    False
118323    False
53346     False
179090    False
138278    False
52104     False
91998     False
163084    False
156668    False
146519    False
21445     False
121824    False
32697     False
19261     False
81506     False
140983    False
139833    False
24534     False
64807     False
75908     False
163911    False
105307    False
38163     False
78169     False
95770     False
80939     False
95870     False
129112    False
48961     False
101476    False
17578     False
78395     False
76740     False
173850    False
71746     False
Name: Latitude, dtype: bool

In [20]:
df_customers['Longitude'].sample(50).isnull()

51367     False
40251     False
23102     False
156613    False
9276      False
14038     False
167664    False
41537     False
44101     False
132787    False
164725    False
170826    False
3725      False
133477    False
72699     False
92721     False
22841     False
157828    False
166428    False
27349     False
53400     False
57635     False
67797     False
31189     False
75069     False
134763    False
27958     False
13856     False
26170     False
14013     False
147394    False
154228    False
174142    False
86743     False
120702    False
164994    False
174957    False
62535     False
150837    False
105128    False
549        True
19991     False
158515    False
122174    False
157792    False
113410    False
21710     False
51307     False
137197    False
145076    False
Name: Longitude, dtype: bool

In [21]:
## Drop columns we do not need 
df_customers.drop(['Customer Email', 'Customer Password', 'Latitude', 'Longitude'], axis = 1, inplace = True)

In [22]:
df_customers

,Customer Id,Customer Fname,Customer Lname,Customer Segment,Customer Country,Customer City,Customer Street,Customer State,Customer Zipcode
0,20755,Cally,Holloway,Consumer,Puerto Rico,Caguas,5365 Noble Nectar Island,PR,72511.0
1,19492,Irene,Luna,Consumer,Puerto Rico,Caguas,2679 Rustic Loop,PR,72511.0
2,19491,Gillian,Maldonado,Consumer,EE. UU.,San Jose,8510 Round Bear Gate,CA,95125.0
3,19490,Tana,Tate,Home Office,EE. UU.,Los Angeles,3200 Amber Bend,CA,90027.0
4,19489,Orli,Hendricks,Corporate,Puerto Rico,Caguas,8671 Iron Anchor Corners,PR,72511.0
...,...,...,...,...,...,...,...,...,...
180514,1005,Maria,Peterson,Home Office,EE. UU.,Brooklyn,1322 Broad Glade,NY,11207.0
180515,9141,Ronald,Clark,Corporate,EE. UU.,Bakersfield,7330 Broad Apple Moor,CA,93304.0
180516,291,John,Smith,Corporate,EE. UU.,Bristol,97 Burning Landing,CT,60101.0
180517,2813,Mary,Smith,Consumer,Puerto Rico,Caguas,2585 Silent Autumn Landing,PR,72511.0
180518,7547,Andrea,Ortega,Consumer,Puerto Rico,Caguas,697 Little Meadow,PR,72511.0

In [23]:
df_customers[df_customers['Customer Zipcode'].isnull()]

,Customer Id,Customer Fname,Customer Lname,Customer Segment,Customer Country,Customer City,Customer Street,Customer State,Customer Zipcode
35704,14577,Sara,Foreman,Consumer,EE. UU.,CA,Elk Grove,95758,NaN
46440,17171,Eugenia,Slater,Corporate,EE. UU.,CA,Elk Grove,95758,NaN
82511,14046,Zena,Elliott,Consumer,EE. UU.,CA,El Monte,91732,NaN

In [24]:
## Fix the 3 shifted rows
## In these rows, the values are in the wrong columns:
## City has the state, State has the zipcode, Street has the city
bad_rows = df_customers['Customer State'].str.isdigit()

## Save the correct values first
correct_city = df_customers.loc[bad_rows, 'Customer Street']
correct_state = df_customers.loc[bad_rows, 'Customer City']
correct_zip = df_customers.loc[bad_rows, 'Customer State'].astype(int)

## Put each value in the right column
df_customers.loc[bad_rows, 'Customer City'] = correct_city
df_customers.loc[bad_rows, 'Customer State'] = correct_state
df_customers.loc[bad_rows, 'Customer Zipcode'] = correct_zip
df_customers.loc[bad_rows, 'Customer Street'] = 'Unknown'

In [25]:
## Check the 3 rows after the fix
df_customers[bad_rows]

,Customer Id,Customer Fname,Customer Lname,Customer Segment,Customer Country,Customer City,Customer Street,Customer State,Customer Zipcode
35704,14577,Sara,Foreman,Consumer,EE. UU.,Elk Grove,Unknown,CA,95758.0
46440,17171,Eugenia,Slater,Corporate,EE. UU.,Elk Grove,Unknown,CA,95758.0
82511,14046,Zena,Elliott,Consumer,EE. UU.,El Monte,Unknown,CA,91732.0

In [26]:
df_customers[df_customers['Customer Lname'].isnull()]

,Customer Id,Customer Fname,Customer Lname,Customer Segment,Customer Country,Customer City,Customer Street,Customer State,Customer Zipcode
41422,17937,May,NaN,Corporate,Puerto Rico,Caguas,690 Cozy Meadow,PR,72511.0
50447,14909,Contreras,NaN,Corporate,EE. UU.,Palatine,2407 Dusty Mount,IL,60067.0
86260,18347,Ray,NaN,Corporate,EE. UU.,Los Angeles,131 Sunny Treasure Green,CA,90027.0
92621,17354,BlueOneal,NaN,Corporate,Puerto Rico,Caguas,9279 Quaking Key,PR,72511.0
97530,14446,York,NaN,Home Office,EE. UU.,San Antonio,2905 Quaking Concession,TX,78240.0
120404,14870,Farley,NaN,Consumer,EE. UU.,Fayetteville,2544 Broad Brook View,NC,28314.0
166129,17929,Le,NaN,Home Office,EE. UU.,Honolulu,8547 Old Drive,HI,96822.0
167119,20439,Huff,NaN,Home Office,EE. UU.,Reseda,7107 Blue Rise Place,CA,91335.0

In [27]:
## Fill the null last names with an empty text
df_customers['Customer Lname'] = df_customers['Customer Lname'].fillna('')

In [28]:
## Add column: Customer Full Name = First name + space + Last name
df_customers['Customer Full Name'] = (df_customers['Customer Fname'] + ' ' + df_customers['Customer Lname']).str.strip()

In [29]:
df_customers['Customer Full Name']

0            Cally Holloway
1                Irene Luna
2         Gillian Maldonado
3                 Tana Tate
4            Orli Hendricks
                ...
180514       Maria Peterson
180515         Ronald Clark
180516           John Smith
180517           Mary Smith
180518        Andrea Ortega
Name: Customer Full Name, Length: 180519, dtype: str

In [30]:
## Drop the two old name columns
df_customers.drop(['Customer Fname', 'Customer Lname'], axis = 1, inplace = True)

In [31]:
df_customers.head()

,Customer Id,Customer Segment,Customer Country,Customer City,Customer Street,Customer State,Customer Zipcode,Customer Full Name
0,20755,Consumer,Puerto Rico,Caguas,5365 Noble Nectar Island,PR,72511.0,Cally Holloway
1,19492,Consumer,Puerto Rico,Caguas,2679 Rustic Loop,PR,72511.0,Irene Luna
2,19491,Consumer,EE. UU.,San Jose,8510 Round Bear Gate,CA,95125.0,Gillian Maldonado
3,19490,Home Office,EE. UU.,Los Angeles,3200 Amber Bend,CA,90027.0,Tana Tate
4,19489,Corporate,Puerto Rico,Caguas,8671 Iron Anchor Corners,PR,72511.0,Orli Hendricks

In [32]:
## Duplicates: how many repeated rows?
df_customers.duplicated().sum()

np.int64(159867)

In [33]:
## Remove the repeated rows
df_customers.drop_duplicates(inplace = True)

In [34]:
df_customers.shape

(20652, 8)

In [35]:
## Is Customer Id unique now?
df_customers['Customer Id'].is_unique

True

In [36]:
## Final check
df_customers.info()
df_customers.head()

<class 'pandas.DataFrame'>
Index: 20652 entries, 0 to 179271
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer Id         20652 non-null  int64
 1   Customer Segment    20652 non-null  str
 2   Customer Country    20652 non-null  str
 3   Customer City       20652 non-null  str
 4   Customer Street     20652 non-null  str
 5   Customer State      20652 non-null  str
 6   Customer Zipcode    20652 non-null  float64
 7   Customer Full Name  20652 non-null  str
dtypes: float64(1), int64(1), str(6)
memory usage: 1.4 MB

,Customer Id,Customer Segment,Customer Country,Customer City,Customer Street,Customer State,Customer Zipcode,Customer Full Name
0,20755,Consumer,Puerto Rico,Caguas,5365 Noble Nectar Island,PR,72511.0,Cally Holloway
1,19492,Consumer,Puerto Rico,Caguas,2679 Rustic Loop,PR,72511.0,Irene Luna
2,19491,Consumer,EE. UU.,San Jose,8510 Round Bear Gate,CA,95125.0,Gillian Maldonado
3,19490,Home Office,EE. UU.,Los Angeles,3200 Amber Bend,CA,90027.0,Tana Tate
4,19489,Corporate,Puerto Rico,Caguas,8671 Iron Anchor Corners,PR,72511.0,Orli Hendricks

In [37]:
## Save the clean table
df_customers.to_csv('DataCo_Customers_Clean.csv', index = False)

## Products Table

####  Explore Data DataCo_Products Table

In [38]:
## How many rows and columns?
df_products.shape

(180519, 11)

In [39]:
## What are the column names?
df_products.columns

Index(['Category Id', 'Category Name', 'Department Id', 'Department Name',
       'Product Card Id', 'Product Category Id', 'Product Description',
       'Product Image', 'Product Name', 'Product Price', 'Product Status'],
      dtype='str')

In [40]:
## What is the data type of each column?
df_products.dtypes

Category Id              int64
Category Name              str
Department Id            int64
Department Name            str
Product Card Id          int64
Product Category Id      int64
Product Description    float64
Product Image              str
Product Name               str
Product Price          float64
Product Status           int64
dtype: object

In [41]:
## Look at the first 5 rows
df_products.head()

,Category Id,Category Name,Department Id,Department Name,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status
0,73,Sporting Goods,2,Fitness,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0
1,73,Sporting Goods,2,Fitness,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0
2,73,Sporting Goods,2,Fitness,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0
3,73,Sporting Goods,2,Fitness,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0
4,73,Sporting Goods,2,Fitness,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0

In [42]:
## Look at the last 5 rows
df_products.tail()

,Category Id,Category Name,Department Id,Department Name,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status
180514,45,Gun Safes,6,Outdoors,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.98,0
180515,45,Gun Safes,6,Outdoors,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.98,0
180516,45,Gun Safes,6,Outdoors,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.98,0
180517,45,Gun Safes,6,Outdoors,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.98,0
180518,45,Gun Safes,6,Outdoors,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.98,0

In [43]:
##  random rows
df_products.sample(3)

,Category Id,Category Name,Department Id,Department Name,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status
61003,48,Kayaks,6,Outdoors,1073,48,NaN,http://images.acmesports.sports/Pelican+Sunstr...,Pelican Sunstream 100 Kayak,199.99,0
35919,38,Fitness Trackers & GPS Watches,10,Technology,303,38,NaN,http://images.acmesports.sports/Garmin+Forerun...,Garmin Forerunner 910XT GPS Watch,399.99,0
152080,45,Gun Safes,6,Outdoors,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.98,0

In [44]:
## data types
df_products.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 11 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Category Id          180519 non-null  int64
 1   Category Name        180519 non-null  str
 2   Department Id        180519 non-null  int64
 3   Department Name      180519 non-null  str
 4   Product Card Id      180519 non-null  int64
 5   Product Category Id  180519 non-null  int64
 6   Product Description  0 non-null       float64
 7   Product Image        180519 non-null  str
 8   Product Name         180519 non-null  str
 9   Product Price        180519 non-null  float64
 10  Product Status       180519 non-null  int64
dtypes: float64(2), int64(5), str(4)
memory usage: 15.1 MB

In [45]:
## Statistics for the number columns
df_products.describe().T

,count,mean,std,min,25%,50%,75%,max
Category Id,180519.0,31.851451,15.640064,2.00,18.0,29.00,45.00,76.00
Department Id,180519.0,4.520643,1.784245,2.00,3.0,5.00,6.00,12.00
Product Card Id,180519.0,692.509764,336.446807,19.00,403.0,627.00,1004.00,1363.00
Product Category Id,180519.0,31.851451,15.640064,2.00,18.0,29.00,45.00,76.00
Product Description,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product Price,180519.0,141.232547,139.732489,9.99,50.0,59.99,199.99,1999.99
Product Status,180519.0,0.000000,0.000000,0.00,0.0,0.00,0.00,0.00

In [46]:
## Statistics for the text columns
df_products.describe(include = 'str').T

,count,unique,top,freq
Category Name,180519,51,Strength Training Equipment,24551
Department Name,180519,11,Outdoors,66816
Product Image,180519,118,http://images.acmesports.sports/Perfect+Fitnes...,24515
Product Name,180519,118,Perfect Fitness Perfect Rip Deck,24515

In [47]:
## How many different values in each column?
df_products.nunique()

Category Id             51
Category Name           51
Department Id           11
Department Name         11
Product Card Id        118
Product Category Id     51
Product Description      0
Product Image          118
Product Name           118
Product Price           75
Product Status           1
dtype: int64

In [48]:
## Unique department names
df_products['Department Name'].unique()

<StringArray>
[          'Fitness',          'Footwear',              'Golf',
        'Technology',          'Outdoors',           'Apparel',
         'Book Shop',        'Discs Shop',          'Pet Shop',
 'Health and Beauty',          'Fan Shop']
Length: 11, dtype: str

In [49]:
## Count the rows of each department
df_products['Department Name'].value_counts()

Department Name
Outdoors             66816
Footwear             48921
Golf                 29570
Fitness              25533
Apparel               4016
Discs Shop            2026
Technology            1849
Fan Shop               529
Pet Shop               492
Book Shop              405
Health and Beauty      362
Name: count, dtype: int64

####  Data Cleaning and Transformation

In [50]:
## Remove extra spaces from all text columns
text_columns = df_products.select_dtypes(exclude = 'number').columns

for col in text_columns:
    df_products[col] = df_products[col].str.strip()

In [51]:
## Missing values: count the nulls in each column
df_products.isna().sum()

Category Id                 0
Category Name               0
Department Id               0
Department Name             0
Product Card Id             0
Product Category Id         0
Product Description    180519
Product Image               0
Product Name                0
Product Price               0
Product Status              0
dtype: int64

In [52]:
## Product Image
df_products['Product Image'].sample(10)

105125    http://images.acmesports.sports/O%27Brien+Men%...
81960     http://images.acmesports.sports/Diamondback+Wo...
132869    http://images.acmesports.sports/O%27Brien+Men%...
124436    http://images.acmesports.sports/Diamondback+Wo...
94177     http://images.acmesports.sports/Field+%26+Stre...
3975      http://images.acmesports.sports/Diamondback+Wo...
30099     http://images.acmesports.sports/Nike+Men%27s+D...
177428    http://images.acmesports.sports/Nike+Men%27s+D...
99244     http://images.acmesports.sports/O%27Brien+Men%...
60641     http://images.acmesports.sports/Field+%26+Stre...
Name: Product Image, dtype: str

In [53]:
## Product Status
df_products['Product Status'].sample(10)

30653     0
21848     0
146623    0
90147     0
174728    0
71773     0
95889     0
7338      0
67044     0
7482      0
Name: Product Status, dtype: int64

In [54]:
## Product Description
df_products['Product Description'].sample(10)

152838   NaN
147374   NaN
177448   NaN
54184    NaN
111720   NaN
29511    NaN
167943   NaN
80336    NaN
87912    NaN
12616    NaN
Name: Product Description, dtype: float64

In [55]:
## Drop useless columns
df_products.drop(['Product Description', 'Product Image', 'Product Status'], axis = 1, inplace = True)

In [56]:
df_products.isna().sum()

Category Id            0
Category Name          0
Department Id          0
Department Name        0
Product Card Id        0
Product Category Id    0
Product Name           0
Product Price          0
dtype: int64

In [57]:
##  Duplicates: how many repeated rows?
df_products.duplicated().sum()

np.int64(180401)

In [58]:
## Remove the repeated rows
df_products.drop_duplicates(inplace = True)

In [59]:
df_products.shape

(118, 8)

In [60]:
df_products

,Category Id,Category Name,Department Id,Department Name,Product Card Id,Product Category Id,Product Name,Product Price
0,73,Sporting Goods,2,Fitness,1360,73,Smart watch,327.75
48,17,Strength Training Equipment,2,Fitness,365,17,Perfect Fitness Perfect Rip Deck,59.99
49,29,Shoes & T-Shirts,3,Footwear,627,29,Under Armour Girls' Toddler Spine Surge Runni,39.99
50,24,Golf Polos,5,Golf,502,24,Nike Men's Dri-FIT Victory Golf Polo,50.00
55,13,Slides & Sandals,3,Footwear,278,13,Under Armour Men's Compression EV SL Slide,44.99
...,...,...,...,...,...,...,...,...
52077,30,Trail & Hiking Shoes,3,Footwear,646,30,Merrell Women's Grassbow Sport Hiking Shoe,99.99
52147,74,Toys,7,Fan Shop,1361,74,Toys,11.54
52676,48,Kayaks,6,Outdoors,1073,48,Pelican Sunstream 100 Kayak,199.99
77012,48,Kayaks,6,Outdoors,1059,48,Pelican Maverick 100X Kayak,349.99
77052,46,Life Vests,6,Outdoors,1014,46,O'Brien Men's Neoprene Life Vest,49.98

In [61]:
## Is Product Card Id unique now?
df_products['Product Card Id'].is_unique

True

In [62]:
## Repeated columns: is Category Id the same as Product Category Id?
(df_products['Category Id'] != df_products['Product Category Id']).sum()

np.int64(0)

In [63]:
## The result is 0, so they are the same. Drop one of them.
df_products.drop('Product Category Id', axis = 1, inplace = True)

In [64]:
df_products.head()

,Category Id,Category Name,Department Id,Department Name,Product Card Id,Product Name,Product Price
0,73,Sporting Goods,2,Fitness,1360,Smart watch,327.75
48,17,Strength Training Equipment,2,Fitness,365,Perfect Fitness Perfect Rip Deck,59.99
49,29,Shoes & T-Shirts,3,Footwear,627,Under Armour Girls' Toddler Spine Surge Runni,39.99
50,24,Golf Polos,5,Golf,502,Nike Men's Dri-FIT Victory Golf Polo,50.00
55,13,Slides & Sandals,3,Footwear,278,Under Armour Men's Compression EV SL Slide,44.99

In [65]:
## Check the price column
df_products['Product Price'].describe()

count     118.000000
mean      166.412966
std       262.184329
min         9.990000
25%        31.990000
50%        87.195000
75%       199.990000
max      1999.990000
Name: Product Price, dtype: float64

In [66]:
## How many prices are zero or negative?
(df_products['Product Price'] <= 0).sum()

np.int64(0)

In [67]:
## Does each Department Id have only one Department Name?
names_per_department = df_products.groupby('Department Id')['Department Name'].nunique()
names_per_department[names_per_department > 1]

Series([], Name: Department Name, dtype: int64)

In [68]:
## Same check for Category Id and Category Name 
names_per_category = df_products.groupby('Category Id')['Category Name'].nunique()
names_per_category[names_per_category > 1]

Series([], Name: Category Name, dtype: int64)

In [69]:
## Does each Product have only one Category Id?
categories_per_product = df_products.groupby('Product Card Id')['Category Id'].nunique()
categories_per_product[categories_per_product > 1]

Series([], Name: Category Id, dtype: int64)

In [71]:
##  Final check
df_products.info()
df_products.head()

<class 'pandas.DataFrame'>
Index: 118 entries, 0 to 77052
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Category Id      118 non-null    int64
 1   Category Name    118 non-null    str
 2   Department Id    118 non-null    int64
 3   Department Name  118 non-null    str
 4   Product Card Id  118 non-null    int64
 5   Product Name     118 non-null    str
 6   Product Price    118 non-null    float64
dtypes: float64(1), int64(3), str(3)
memory usage: 7.4 KB

,Category Id,Category Name,Department Id,Department Name,Product Card Id,Product Name,Product Price
0,73,Sporting Goods,2,Fitness,1360,Smart watch,327.75
48,17,Strength Training Equipment,2,Fitness,365,Perfect Fitness Perfect Rip Deck,59.99
49,29,Shoes & T-Shirts,3,Footwear,627,Under Armour Girls' Toddler Spine Surge Runni,39.99
50,24,Golf Polos,5,Golf,502,Nike Men's Dri-FIT Victory Golf Polo,50.00
55,13,Slides & Sandals,3,Footwear,278,Under Armour Men's Compression EV SL Slide,44.99

In [72]:
## Save the clean table
df_products.to_csv('DataCo_Products_Clean.csv', index = False)

# Order_Items Table

 ####  Explore Data DataCO_Orders_Item Table

In [73]:
## How many rows and columns?
df_orders.shape

(180519, 31)

In [74]:
## What are the column names?
df_orders.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Customer Id', 'Market', 'Order City',
       'Order Country', 'Order Customer Id', 'order date (DateOrders)',
       'Order Id', 'Order Item Cardprod Id', 'Order Item Discount',
       'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price',
       'Order Item Profit Ratio', 'Order Item Quantity', 'Sales',
       'Order Item Total', 'Order Profit Per Order', 'Order Region',
       'Order State', 'Order Status', 'Order Zipcode', 'Product Card Id',
       'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='str')

In [75]:
## What is the data type of each column?
df_orders.dtypes

Type                                 str
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                      str
Late_delivery_risk                 int64
Customer Id                        int64
Market                               str
Order City                           str
Order Country                        str
Order Customer Id                  int64
order date (DateOrders)              str
Order Id                           int64
Order Item Cardprod Id             int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Id                      int64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                         str
Order State                          str
Order Status                         str
Order Zipcode                    float64
Product Card Id                    int64
shipping date (DateOrders)           str
Shipping Mode                        str
dtype: object

In [76]:
## Look at the first 5 rows
df_orders.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Customer Id,Market,Order City,...,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Order Zipcode,Product Card Id,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.25,314.64,Advance shipping,0,20755,Pacific Asia,Bekasi,...,327.75,314.64,91.25,Southeast Asia,Java Occidental,COMPLETE,NaN,1360,43161.95556,Standard Class
1,TRANSFER,5,4,-249.09,311.36,Late delivery,1,19492,Pacific Asia,Bikaner,...,327.75,311.36,-249.09,South Asia,Rajastan,PENDING,NaN,1360,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.78,309.72,Shipping on time,0,19491,Pacific Asia,Bikaner,...,327.75,309.72,-247.78,South Asia,Rajastan,CLOSED,NaN,1360,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.86,304.81,Advance shipping,0,19490,Pacific Asia,Townsville,...,327.75,304.81,22.86,Oceania,Queensland,COMPLETE,NaN,1360,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.21,298.25,Advance shipping,0,19489,Pacific Asia,Townsville,...,327.75,298.25,134.21,Oceania,Queensland,PENDING_PAYMENT,NaN,1360,1/15/2018 11:24,Standard Class

In [77]:
## Look at the last 5 rows
df_orders.tail()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Customer Id,Market,Order City,...,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Order Zipcode,Product Card Id,shipping date (DateOrders),Shipping Mode
180514,CASH,4,4,40.00,399.98,Shipping on time,0,1005,Pacific Asia,Shanghai,...,399.98,399.98,40.00,Eastern Asia,Shanghai,CLOSED,NaN,1004,1/20/2016 3:40,Standard Class
180515,DEBIT,3,2,-613.77,395.98,Late delivery,1,9141,Pacific Asia,Hirakata,...,399.98,395.98,-613.77,Eastern Asia,Osaka,COMPLETE,NaN,1004,1/19/2016 1:34,Second Class
180516,TRANSFER,5,4,141.11,391.98,Late delivery,1,291,Pacific Asia,Adelaide,...,399.98,391.98,141.11,Oceania,Australia del Sur,PENDING,NaN,1004,1/20/2016 21:00,Standard Class
180517,PAYMENT,3,4,186.23,387.98,Advance shipping,0,2813,Pacific Asia,Adelaide,...,399.98,387.98,186.23,Oceania,Australia del Sur,PENDING_PAYMENT,NaN,1004,1/18/2016 20:18,Standard Class
180518,PAYMENT,4,4,168.95,383.98,Shipping on time,0,7547,Pacific Asia,Nagercoil,...,399.98,383.98,168.95,South Asia,Tamil Nadu,PENDING_PAYMENT,NaN,1004,1/19/2016 18:54,Standard Class

In [78]:
## random rows
df_orders.sample(3)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Customer Id,Market,Order City,...,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Order Zipcode,Product Card Id,shipping date (DateOrders),Shipping Mode
35296,CASH,2,4,67.49,224.96,Advance shipping,0,7787,Africa,Kikwit,...,299.95,224.96,67.49,Central Africa,Bandundu,CLOSED,NaN,365,12/31/2016 3:11,Standard Class
35624,DEBIT,2,1,11.20,128.69,Late delivery,1,5529,Africa,Jartum,...,129.99,128.69,11.20,North Africa,Jartum,COMPLETE,NaN,403,10/30/2016 19:44,First Class
180100,DEBIT,2,2,100.00,399.98,Shipping on time,0,9748,Pacific Asia,Depok,...,399.98,399.98,100.00,Southeast Asia,Yogyakarta,COMPLETE,NaN,1004,42645.91806,Second Class

In [79]:
## data types
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 31 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Customer Id                    180519 non-null  int64
 8   Market                         180519 non-null  str
 9   Order City                     180519 non-null  str
 10  Order Country                  180519 non-null  str
 11  Order Customer Id              180519 non-null  int64
 12  order date (DateOrders)        180519 non-null  str
 13  Order Id                       180519 non-null  int64
 14  Order Item Cardprod Id         180519 non-null  int64
 15  Order Item Discount            180519 non-null  float64
 16  Order Item Discount Rate       180519 non-null  float64
 17  Order Item Id                  180519 non-null  int64
 18  Order Item Product Price       180519 non-null  float64
 19  Order Item Profit Ratio        180519 non-null  float64
 20  Order Item Quantity            180519 non-null  int64
 21  Sales                          180519 non-null  float64
 22  Order Item Total               180519 non-null  float64
 23  Order Profit Per Order         180519 non-null  float64
 24  Order Region                   180519 non-null  str
 25  Order State                    180519 non-null  str
 26  Order Status                   180519 non-null  str
 27  Order Zipcode                  24840 non-null   float64
 28  Product Card Id                180519 non-null  int64
 29  shipping date (DateOrders)     180519 non-null  str
 30  Shipping Mode                  180519 non-null  str
dtypes: float64(10), int64(10), str(11)
memory usage: 42.7 MB

In [80]:
## Statistics for the number columns
df_orders.describe().T

,count,mean,std,min,25%,50%,75%,max
Days for shipping (real),180519.0,3.497654,1.623722,0.00,2.00,3.00,5.00,6.00
Days for shipment (scheduled),180519.0,2.931847,1.374449,0.00,2.00,4.00,4.00,4.00
Benefit per order,180519.0,21.974989,104.433526,-4274.98,7.00,31.52,64.80,911.80
Sales per customer,180519.0,183.107607,120.043668,7.49,104.38,163.99,247.40,1939.99
Late_delivery_risk,180519.0,0.548291,0.497664,0.00,0.00,1.00,1.00,1.00
Customer Id,180519.0,6691.379495,4162.918106,1.00,3258.50,6457.00,9779.00,20757.00
Order Customer Id,180519.0,6691.379495,4162.918106,1.00,3258.50,6457.00,9779.00,20757.00
Order Id,180519.0,36221.894903,21045.379569,1.00,18057.00,36140.00,54144.00,77204.00
Order Item Cardprod Id,180519.0,692.509764,336.446807,19.00,403.00,627.00,1004.00,1363.00
Order Item Discount,180519.0,20.664741,21.800901,0.00,5.40,14.00,29.99,500.00
Order Item Discount Rate,180519.0,0.101668,0.070415,0.00,0.04,0.10,0.16,0.25
Order Item Id,180519.0,90260.000000,52111.490959,1.00,45130.50,90260.00,135389.50,180519.00
Order Item Product Price,180519.0,141.232547,139.732489,9.99,50.00,59.99,199.99,1999.99
Order Item Profit Ratio,180519.0,0.120647,0.466796,-2.75,0.08,0.27,0.36,0.50
Order Item Quantity,180519.0,2.127638,1.453451,1.00,1.00,1.00,3.00,5.00
Sales,180519.0,203.772092,132.273075,9.99,119.98,199.92,299.95,1999.99
Order Item Total,180519.0,183.107607,120.043668,7.49,104.38,163.99,247.40,1939.99
Order Profit Per Order,180519.0,21.974989,104.433526,-4274.98,7.00,31.52,64.80,911.80
Order Zipcode,24840.0,55426.132327,31919.279101,1040.00,23464.00,59405.00,90008.00,99301.00
Product Card Id,180519.0,692.509764,336.446807,19.00,403.00,627.00,1004.00,1363.00

In [81]:
## Statistics for the text columns
df_orders.describe(include = 'str').T

                             count unique               top    freq
Type                        180519      4             DEBIT   69295
Delivery Status             180519      4     Late delivery   98977
Market                      180519      5             LATAM   51594
Order City                  180519   3596     Santo Domingo    2211
Order Country               180519    164     United States   24840
order date (DateOrders)     180519  65752  10/25/2016 14:39       5
Order Region                180519     23   Central America   28341
Order State                 180519   1088        Inglaterra    6722
Order Status                180519      9          COMPLETE   59491
shipping date (DateOrders)  180519  63701       42252.75139      10
Shipping Mode               180519      4    Standard Class  107752

In [82]:
## How many different values in each column?
df_orders.nunique()

Type                                  4
Days for shipping (real)              7
Days for shipment (scheduled)         4
Benefit per order                 21998
Sales per customer                 2927
Delivery Status                       4
Late_delivery_risk                    2
Customer Id                       20652
Market                                5
Order City                         3596
Order Country                       164
Order Customer Id                 20652
order date (DateOrders)           65752
Order Id                          65752
Order Item Cardprod Id              118
Order Item Discount                1017
Order Item Discount Rate             18
Order Item Id                    180519
Order Item Product Price             75
Order Item Profit Ratio             162
Order Item Quantity                   5
Sales                               193
Order Item Total                   2927
Order Profit Per Order            21998
Order Region                         23
Order State                        1088
Order Status                          9
Order Zipcode                       609
Product Card Id                     118
shipping date (DateOrders)        63701
Shipping Mode                         4
dtype: int64

In [83]:
## Unique values in the small text columns
df_orders['Type'].unique()

<StringArray>
['DEBIT', 'TRANSFER', 'CASH', 'PAYMENT']
Length: 4, dtype: str

In [84]:
df_orders['Delivery Status'].unique()

<StringArray>
['Advance shipping', 'Late delivery', 'Shipping on time', 'Shipping canceled']
Length: 4, dtype: str

In [85]:
df_orders['Market'].unique()

<StringArray>
['Pacific Asia', 'USCA', 'Africa', 'Europe', 'LATAM']
Length: 5, dtype: str

In [86]:
df_orders['Shipping Mode'].unique()

<StringArray>
['Standard Class', 'First Class', 'Second Class', 'Same Day']
Length: 4, dtype: str

In [87]:
df_orders['Order Status'].unique()

<StringArray>
[       'COMPLETE',         'PENDING',          'CLOSED', 'PENDING_PAYMENT',
        'CANCELED',      'PROCESSING', 'SUSPECTED_FRAUD',         'ON_HOLD',
  'PAYMENT_REVIEW']
Length: 9, dtype: str

In [88]:
## Count the rows of each delivery status
df_orders['Delivery Status'].value_counts()

Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

#### Data Cleaning and Transformation Order_Items Table

In [89]:
## Remove extra spaces from all text columns
text_columns = df_orders.select_dtypes(exclude = 'number').columns

for col in text_columns:
    df_orders[col] = df_orders[col].str.strip()

In [90]:
##  Missing values: count the nulls in each column
df_orders.isna().sum()

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Customer Id                           0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

In [91]:
#Order Zipcode
df_orders['Order Zipcode'].sample(10)

174103        NaN
114534        NaN
85162         NaN
108110        NaN
23016         NaN
169412        NaN
109571    19120.0
179062        NaN
93290         NaN
173119     4401.0
Name: Order Zipcode, dtype: float64

In [92]:
## what percent is null?
df_orders['Order Zipcode'].isna().mean() * 100

np.float64(86.23967560201419)

In [93]:
#Benefit per order vs Order Profit Per Order 
((df_orders['Benefit per order'] - df_orders['Order Profit Per Order']) > 0).sum()

np.int64(0)

In [94]:
#Sales per customer vs Order Item Total
((df_orders['Sales per customer'] - df_orders['Order Item Total']) > 0).sum()

np.int64(0)

In [95]:
#Order Customer Id vs Customer Id
(df_orders['Order Customer Id'] != df_orders['Customer Id']).sum()

np.int64(0)

In [96]:
#Order Item Cardprod Id vs Product Card Id
(df_orders['Order Item Cardprod Id'] != df_orders['Product Card Id']).sum()

np.int64(0)

In [97]:
## [ Drop the 5 columns : Order Zipcode  + 4 repeated columns
df_orders.drop(['Order Zipcode', 'Benefit per order', 'Sales per customer', 'Order Customer Id', 'Order Item Cardprod Id'], axis = 1, inplace = True)

In [98]:
df_orders.shape

(180519, 26)

In [99]:
##  Duplicates: how many repeated rows?
df_orders.duplicated().sum()

np.int64(0)

In [100]:
##  Is Order Item Id unique? 
df_orders['Order Item Id'].is_unique

True

In [101]:
## How many orders?
df_orders['Order Id'].nunique()

65752

In [102]:
## How many customers?
df_orders['Customer Id'].nunique()

20652

In [103]:
## How many products?
df_orders['Product Card Id'].nunique()

118

In [104]:
## Negative profit: how many rows lose money?
(df_orders['Order Profit Per Order'] < 0).sum()

np.int64(33784)

##### Edit order date Type

In [105]:
## Edit The date Type
is_number_order = df_orders['order date (DateOrders)'].str.fullmatch(r'\d+(\.\d+)?')
print('Excel numbers :', is_number_order.sum(), ' Text dates :', (~is_number_order).sum())
df_orders.loc[is_number_order, 'order date (DateOrders)'].head()

Excel numbers : 71103  Text dates : 109416

37    43435.99375
38    43435.97917
39    43435.96458
40       43435.95
41    43435.93542
Name: order date (DateOrders), dtype: str

In [ ]:
##  Step 1 : text dates -> real dates (the text format is month/day/year)
text_dates = pd.to_datetime(df_orders.loc[~is_number_order, 'order date (DateOrders)'], format = '%m/%d/%Y %H:%M')

## Step 2 : Excel numbers -> real dates (Excel day 0 = 1899-12-30), rounded to the minute
excel_dates = pd.to_datetime('1899-12-30') + pd.to_timedelta(df_orders.loc[is_number_order, 'order date (DateOrders)'].astype(float), unit = 'D')
excel_dates = excel_dates.dt.round('min')

## Step 3 : in the Excel dates the DAY and the MONTH are swapped (ex: 3 Feb 2018 was saved as 2 Mar 2018 = 43161). Swap them back
excel_dates = pd.to_datetime(dict(year = excel_dates.dt.year, month = excel_dates.dt.day, day = excel_dates.dt.month, hour = excel_dates.dt.hour, minute = excel_dates.dt.minute))

## Step 4 : put the 2 parts back in the table (the index keeps the same row order)
df_orders['order date (DateOrders)'] = pd.concat([text_dates, excel_dates]).sort_index()

##### Edit Shipping date Type

In [ ]:
## [EDIT] Same 4 steps for the shipping date (it has the same 2 formats)
is_number_ship = df_orders['shipping date (DateOrders)'].str.fullmatch(r'\d+(\.\d+)?')
print('Excel numbers :', is_number_ship.sum(), ' Text dates :', (~is_number_ship).sum())

text_dates = pd.to_datetime(df_orders.loc[~is_number_ship, 'shipping date (DateOrders)'], format = '%m/%d/%Y %H:%M')

excel_dates = pd.to_datetime('1899-12-30') + pd.to_timedelta(df_orders.loc[is_number_ship, 'shipping date (DateOrders)'].astype(float), unit = 'D')
excel_dates = excel_dates.dt.round('min')

excel_dates = pd.to_datetime(dict(year = excel_dates.dt.year, month = excel_dates.dt.day, day = excel_dates.dt.month, hour = excel_dates.dt.hour, minute = excel_dates.dt.minute))

df_orders['shipping date (DateOrders)'] = pd.concat([text_dates, excel_dates]).sort_index()

##### Check the dates

In [ ]:
# Type
df_orders['order date (DateOrders)'].dtype

In [ ]:
# nulls
df_orders['order date (DateOrders)'].isna().sum()

In [ ]:
# first date
df_orders['order date (DateOrders)'].min()

In [ ]:
# last date
df_orders['order date (DateOrders)'].max()

In [ ]:
# Type
df_orders['shipping date (DateOrders)'].dtype

In [ ]:
# nulls
df_orders['shipping date (DateOrders)'].isna().sum()

In [ ]:
## Shipping date must not be before order date 
(df_orders['shipping date (DateOrders)'] < df_orders['order date (DateOrders)']).sum()

In [ ]:
# first date
df_orders['shipping date (DateOrders)'].min()

In [ ]:
# last date
df_orders['shipping date (DateOrders)'].max()

##### Validation: do the numbers agree with each other?

In [ ]:
## Sales must equal Price x Quantity 
((df_orders['Sales'] - df_orders['Order Item Product Price'] * df_orders['Order Item Quantity']) > 0.02).sum()

In [ ]:
## Order Item Total must equal Sales - Discount 
((df_orders['Order Item Total'] - (df_orders['Sales'] - df_orders['Order Item Discount'])) > 0.02).sum()

In [ ]:
## Every Customer Id in orders must exist in the other tables 
df_orders['Customer Id'].isin(df_customers['Customer Id']).all()

In [ ]:
## Every Product Card Id in orders must exist in the other tables
df_orders['Product Card Id'].isin(df_products['Product Card Id']).all()

In [ ]:
## The price in orders must match the price in the Products table 
product_price = df_orders['Product Card Id'].map(df_products.set_index('Product Card Id')['Product Price'])
((df_orders['Order Item Product Price'] - product_price) > 0.01).sum()

In [ ]:
## Final check
print(df_orders.shape)

In [ ]:
df_orders.isna().sum()

In [ ]:
## Save the clean table
df_orders.to_csv('DataCo_Order_Items_Clean.csv', index = False)

In [ ]:
print(df_orders.shape)

In [ ]:
df_orders.isna().sum()

In [ ]:
## Save the clean table
df_orders.to_csv('DataCo_Order_Items_Clean.csv', index = False)